### ISSUE TITLE
maximum step size setting

### ISSUE THREAD

**Issue by jtravs** [headmyshoulder/odeint-v2#122]
I may have missed it in the documentation, but is there a way to set the maximum step size? For some problems it is necessary to prevent the adaptive stepper from missing out fast events (I can provide an example). Currently I am using integrate_const as a workaround, but that strongly couples the observer output to the upper step size I would like.

**Comment by mariomulansky** [comment]
This new functionality has been included in #177 and will be part of the next release (Boost 1.60)
