### ISSUE TITLE
Custom break conditions

### ISSUE THREAD

**Issue by konstantinmiller** [headmyshoulder/odeint-v2#123]
Hi!

I would like to interrupt integration if system state satisfies certain conditions (proximity to a certain set of points).

I found your comment on StackOverflow stating that you were going to implement integrate routines accepting custom break conditions. The comment is from 2013 and it is saying that such routines should appear in few weeks.

I just browsed through odeint documentation but could not find this feature. Could you please give me a hint?

Thanks!

Best
Konstantin Miller

**Comment by mariomulansky** [comment]
Please also see Issue #9 for more discussion on this.
