### ISSUE TITLE
Bug in velocity-verlet

### ISSUE THREAD

**Issue by mariomulansky** [headmyshoulder/odeint-v2#150]
There is possibly a bug in the velocity-verlet algorithm.
In velocity-verlet.hpp, line 115:
```
algebra_stepper_base_type::m_algebra.for_each4(
            qout , qin , pin , ain ,
            typename operations_type::template scale_sum3< value_type , time_type , time_square_type >( one , one_half * dt , one * dt * dt ) );
```
it should be ```one * dt``` and ```one_half * dt * dt```

**Comment by headmyshoulder** [comment]
Yeah, this is a bug. I will fix it.

**Comment by ddemidov** [comment]
How serious is it? Should I rerun any experiments depending on velocity-verlet?

**Comment by mariomulansky** [comment]
probably :(

**Comment by ddemidov** [comment]
Thanks, good to know :)

**Comment by headmyshoulder** [comment]
Yes, you should :(
