### ISSUE TITLE
Error in documentation for parallel OMP/MPI calculation

### ISSUE THREAD

**Issue by Wentzell** [headmyshoulder/odeint-v2#164]
In the documentation
http://headmyshoulder.github.io/odeint-v2/doc/boost_numeric_odeint/tutorial/parallel_computation_with_openmp_and_mpi.html
the second code box in the MPI does not make any sense in the MPI context, it is rather just the same as the previously shown example from the OMP part. I suppose this is not intentional?

Greetings

**Comment by mariomulansky** [comment]
Indeed, there was a typo in the docs such that the wrong source snippet got included. Thanks for reported, should be fixed.
