### ISSUE TITLE
Citing odeint

### ISSUE THREAD

**Issue by MatthiasKauer** [headmyshoulder/odeint-v2#188]
Hi,
I'm wondering if you have a preference for how odeint should be cited.
I have found the following article on arxiv:
```
@article{ahnert_odeint-solving_2011,
	title = "{Odeint -- Solving Ordinary Differential Equations in C++}",
	journal = {arXiv preprint arXiv:1110.3397},
	author = {Ahnert, Karsten and Mulansky, Mario},
	year = {2011},
}
```
Should it be cited in that way?

Kind regards,
Matthias

**Comment by mariomulansky** [comment]
Our preferred reference is this one:

K. Ahnert and M. Mulansky, Odeint - Solving Ordinary Differential Equations in C++, AIP Conf. Proc. 1389, pp. 1586-1589 (2011);
doi:http://dx.doi.org/10.1063/1.3637934

Recently, we also published an odeint article on scholarpedia that is also citable: http://www.scholarpedia.org/article/Odeint_library

**Comment by MatthiasKauer** [comment]
thank you
