### ISSUE TITLE
example stiff_system.cpp performance

### ISSUE THREAD

**Issue by xlai** [headmyshoulder/odeint-v2#189]
Hi,
I followed the example without any change and compiled it with g++ 5.2.1. Using the rosenbrock4 stepper, it finishes in 40030 steps rather than 71 steps, as described in the document. The dopri5 stepper finishes in 1531 steps which agrees with the document. I'm not sure where it went wrong.

Thank you!

**Comment by mariomulansky** [comment]
I can confirm this observation. This is definitely some bug, I will look into this.

**Comment by bjodah** [comment]
@mariomulansky do you know when this fix will be in boost? (it's not in 1.62 released end of august..)
