### ISSUE TITLE
rosenbrock4 integrate_adaptive hangs

### ISSUE THREAD

**Issue by bjodah** [headmyshoulder/odeint-v2#193]
I have bisected the regression to 60cd098 using the test suite of my Python bindings:
https://github.com/bjodah/pyodeint/pull/20

I have tried to find a bug in the 60cd098, but I guess this is a subtle issue, any ideas?

**Comment by mariomulansky** [comment]
Can you extract a short test program that I could use to investigate the bug in odeint?

**Comment by bjodah** [comment]
Sure (it might have to wait to the weekend though). Thanks!

**Comment by bjodah** [comment]
So I finally got around writing a test program for this. Turns out I was using the API incorrectly, it just happened to work for the wrong reasons. Closing this, sorry for the noise.
