### ISSUE TITLE
varying absolute tolerances

### ISSUE THREAD

**Issue by wds15** [headmyshoulder/odeint-v2#204]
Hi!

Currently we can use the adaptive integration schemes with a single relative and absolute error tolerance which holds for all states at the same time.

In my application I do know that the scale of the sates differs systematically. Hence, I would like to be able to set per integrated state the absolute tolerance separately. I have not found this in the docs and it would be great if this could be considered.

**Comment by mariomulansky** [comment]
This is not supported out-of-the box in odeint right now. We decided against this for the sake of an easier interface. However, it should be quite easy to add such functionality. You would need to implement a new error checker, and provide it as template parameter to the adaptive stepper you are using. The default error checker is documented there: http://headmyshoulder.github.io/odeint-v2/doc/boost/numeric/odeint/default_error_checker.html
The new error_checker should provide the same interface, but use a vector for the absolute/relative error to allow for the different scales.

**Comment by wds15** [comment]
Great. Thanks. Just about anything is customizable in odeint. Wonderful.

**Comment by martinkrausze** [comment]
I would like to scale my ode problem. Alternatively I could use different absolute/relative error values for the 2 components of my state vector of my solution. Mario Mulansky wrote, this functionality could be added easily by implementing a new error checker. Can anyone give me an example? Thanks a lot.
