### ISSUE TITLE
Bulirsch-Stoer constructor question

### ISSUE THREAD

**Issue by kartikkumar** [headmyshoulder/odeint-v2#211]
I'm not able to track this down in the documentation, nor really parse it out of the reference text (Hairer et al.). 

I was wondering if someone can shed light on what the `factor_x` and `factor_dxdt` terms are. They are set in this example in `bulirsch_stoer.cpp` to `0.0` and in `elliptic_functions.cpp` to `1.0` and `0.0` respectively.

Any insights would be greatly appreciated.

**Comment by mariomulansky** [comment]
Great question. Those variables are not actually used in the algorithm at the moment (which means they are implicitly set to 1). They are part of the interface already, but we never got around to pass them through into the algorithm. I'm not sure about their actual meaning either at this point.
