### ISSUE TITLE
Missing ending point with dopri5 (dense output)

### ISSUE THREAD

**Issue by brankaleon** [headmyshoulder/odeint-v2#220]
I'm using dense output to get the value of the system state at large, constant time steps.
However, the endpoint is not getting evaluated.

typedef result_of::make_dense_output<runge_kutta_dopri5<state_type>>::type my_dense_stepper_type;
my_dense_stepper_type	   dense2 = make_dense_output(1.0e-6, 1.0e-6, runge_kutta_dopri5< state_type >());
t0 = 0.; tf=1.; dt = 0.2;
integrate_const(make_dense_output(1.0e-6, 1.0e-6, runge_kutta_dopri5< state_type >()), rhs, x0, t0, tf, dt, write_cout);

On the other hand, if i use "integrate_adaptive" the endpoint is evaluated and printed out

**Comment by mariomulansky** [comment]
This is probably due to finite precision. If you call integrate_const with tf+dt/2 you should see tf as the last evaluation point. However, if you want to take exactly 5 steps with dt=0.2 you should use integrate_n_steps instead of integrate_conts
