### ISSUE TITLE
Adapter file for eigen3

### ISSUE THREAD

**Issue by sanjayankur31** [headmyshoulder/odeint-v2#68]
Hi headmyshoulder,

As discussed at the [stackoverflow question] (http://stackoverflow.com/questions/14207698/should-i-switch-to-mtl4-from-eigen-if-i-also-need-to-make-use-of-odes), I've attempted to adapt the resizing mechanism of odeint to work with eigen3. The source file is [here] (http://ankursinha.fedorapeople.org/odeint/eigen3_resize.hpp). While it looks okay, I'm not quite sure if it's complete:

Eigen provides a special row and col type -> Eigen::Dynamic which implies that the matrix/array will not be given dimensions at compile time, rather at runtime. Should I take this into consideration? In this case, the code would look like this:

```C++
template<typename _Scalar, int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols>
struct is_resizeable< Eigen::Array <typename _Scalar, int _Rows, int _Cols, int _Options, int _MaxRows, int _MaxCols> >
{ 
    typedef boost::true_type type;
    const static bool value = type::value;
    if ((_Rows != Eigen::Dynamic ) && (_Cols != Eigen::Dynamic))
        value = boost::false_type::value;
};
```
Another quirk worth mentioning is that Martices and Arrays cannot operate with one another automatically (even if they're of the same dimensions). One needs to explicitly convert them into matrices or arrays before arithmetic operations can be made on them:

```C++
array1 = array2 + matrix1.array(); // matrix to array
```
I haven't tested the adapter yet, so I cannot confirm if the current header is sufficient, or snippets like above need to be added. I'll let you know whenever I get down to doing it. I'm still figuring out how to use odeint at the moment. 

The eigen documentation is [here](http://eigen.tuxfamily.org/dox/GettingStarted.html). If you have the cycles, please do check my code. It'll benefit me greatly ;)

I've also packaged odeint for fedora. Boost 1.53 will only be available in Fedora 19, which is 6 months away. Until then, I'll maintain a odeint package for F <= 18. The rpms are available [here](http://ankursinha.fedorapeople.org/odeint/). Feel free to use/distribute them. They haven't been reviewed yet. The review ticket is open [here](https://bugzilla.redhat.com/show_bug.cgi?id=896310)

I hope the header and rpms help you.

Thanks,
Warm regards,
Ankur (FranciscoD)

**Comment by mariomulansky** [comment]
Merged there: https://github.com/headmyshoulder/odeint-v2/pull/74
